/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_codec_VideoEncoder */

#ifndef _Included_com_lmy_ffmpeg_codec_VideoEncoder
#define _Included_com_lmy_ffmpeg_codec_VideoEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_codec_VideoEncoder
 * Method:    init
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_lmy_ffmpeg_codec_VideoEncoder_init
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_lmy_ffmpeg_codec_VideoEncoder
 * Method:    encode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_codec_VideoEncoder_encode
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_lmy_ffmpeg_codec_VideoEncoder
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_codec_VideoEncoder_flush
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
