/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_codec_AudioDecoder */

#ifndef _Included_com_lmy_ffmpeg_codec_AudioDecoder
#define _Included_com_lmy_ffmpeg_codec_AudioDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_codec_AudioDecoder
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;Lcom/lmy/ffmpeg/codec/AVFrame;)V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_codec_AudioDecoder_setDataSource
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_lmy_ffmpeg_codec_AudioDecoder
 * Method:    nextFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lmy_ffmpeg_codec_AudioDecoder_nextFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_lmy_ffmpeg_codec_AudioDecoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_codec_AudioDecoder_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
